UofTCoders/council

swc/attendance.csv
Started a dataset of attendance and registration
=> Added attendance and registered for SWC workshops

treasurer/reimbursing/README.md, treasurer/reimbursing/template.md
Comments? Thoughts? Seems fairly simple I think...
=> Reimbursement steps

treasurer/accounting.csv, treasurer/cheques/cheques.csv, treasurer/reimbursing/submitted/2016-06-02-dawn-walker.md
I'm submitting this for @dcwalk. @mbonsma could you approve this PR? Also, you around to sign cheque this Monday?
=> Reimburse Dawn Walker (@dcwalk)

treasurer/accounting.csv, treasurer/cheques/cheques.csv, treasurer/reimbursing/submitted/2016-06-06-madeleine-bonsma.md
This is so @mbonsma doesn't forget that she paid for drinks at the social. So I did it for you since I have the receipt and already got the GPG signing thingy.
@linamnt could you approve this PR for record keeping? ..since the cheque is going to Maddy. a +1 works or a comment.
=> Reimburse Maddy for the pub drinks

Council_Roles.md
Add as needed the duties! :smile:
=> Added new role for @lcoome

swc/attendance.csv
Forgot to add this after the session
=> Added numbers who came to SWC workshop

treasurer/README.Rmd, treasurer/README.md, treasurer/accounting.csv, treasurer/reimbursing/submitted/2016-07-04-madeleine-bonsma.md, treasurer/reimbursing/template.md
Plus updated the treasury readme
=> Updated reimbursing template and added approval persons for prev PR

Attendance.csv
The number of attendees is +-1, I estimated based on who I remember being there.
=> Add intro git numbers to attendance

course/meetings/cs-francois-pitt-2017-03-14.md
@lwjohnst86 @mbonsma Check that this is what you got from the meeting.
@mbonsma Feel free to remove your action item if it is not relevant.
=> Added cs-minutes

course/meetings/uoftcoders-2017-03-15.md
This is the same as the email I sent to Asher
=> Added notes from yesterday

course/meetings/mie-matthew-mackay-2017-03-13.md
@mbonsma check that this represents what we heard.
=> Added minutes on mie meeting

meetings/Agenda_2017-03-22.md
Feel free to suggest changes / additions.
=> Agenda for 2017-03-22 council meeting

course/meetings/eeb-marty-asher-2017-03-30.md
Accidentally made this as a branch on the UofTcoders repo instead of my own fork. But I guess it doesn't matter that much for this time.
=> Added notes from eeb meeting today

Constitution.md
=> Constitution update, particularly for audit of finances

outreach_announcement.md
=> Updated outreach blurb 

treasurer/README.Rmd, treasurer/README.md, treasurer/accounting.csv, treasurer/cheques/cheques.csv
- added cheques used (and nulled)
- added bank fees
- updated readme (removed code chunks from output)
=> Treasury updates

meetings/Minutes_2017-08-09.md
some action items have actually been completed so don't mind those, just record-keeping.
=> minutes Aug 9 2017

meetings/Agenda_2017-09-03.md
@joelostblom - do you want to flesh out the RQM section of this?
=> Meeting agenda for Sept 3

meetings/Agenda_2017-12-11.md
Feel free to add things / suggest changes.
=> Agenda for Dec 11 meeting

treasurer/banking/README.md, treasurer/banking/change-signing-officers.md
Plus a readme for dealing with some things with the bank.
=> Bank letter to change signing officers

admin/lesson-setup.md
=> make setup file

Council_Roles.md
* Add key caretaking and managing exec presence at events to president and admin
* Add marketing role
* Add peer mentorship coordinator role
=> Updates to council roles

meetings/Agenda_2022-01-12.md, meetings/Minutes_2021-12-08.md, meetings/Minutes_2022-01-12.md
(also fix date in previous meeting minutes - whoops!)
=> Add Jan 2022 meeting agenda + minutes

meetings/Minutes_2022-05-30.md
=> Incorporate May 2022 meeting minutes review

Council_Roles.md, meetings/Agenda_2022-10-03.md, meetings/Minutes_2022-10-03.md
=> Add Oct meeting agenda

meetings/Agenda_2022-12-05.md, meetings/Minutes_2022-12-05.md
Let me know if anything should be changed/added!
=> Add Dec 2022 meeting agenda/minutes

meetings/Agenda_2022-10-11.md, meetings/Minutes_2022-10-11.md
=> Add agenda for followup Oct meeting
